insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (40, 'The Bell Jar', 2014, 'disappointing', 145, 'comedy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (41, 'The Lovely Bones', 2005, 'unsatisfying', 90, 'psychological');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (42, 'The Great Expectations', 2009, 'mediocre', 165, 'spy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (43, 'The Maze Runner', 2005, 'disappointing', 45, 'horror');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (44, 'The Great Gatsby', 1997, 'good', 185, 'music');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (45, 'The Sun Also Rises', 2014, 'impressive', 85, 'comedy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (46, 'Pride and Prejudice', 2018, 'remarkable', 135, 'mystery');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (47, 'The Sound and the Fury', 2008, 'lousy', 35, 'spy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (48, 'To Kill a Mockingbird', 1991, 'awful', 120, 'satire');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (49, 'The Great Gatsby', 2013, 'impressive', 50, 'zombie');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (50, 'The Kite Runner', 2011, 'decent', 120, 'time travel');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (51, 'The Color Purple', 2025, 'superior', 5, 'musical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (52, '1984', 2000, 'bad', 145, 'historical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (53, 'The Chronicles of Narnia', 2024, 'first-rate', 75, 'musical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (54, 'The Great Expectations', 2009, 'satisfactory', 105, 'political');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (55, 'The Help', 2005, 'outstanding', 185, 'comedy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (56, 'The Old Man and the Sea', 1995, 'outstanding', 105, 'suspense');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (57, 'The Old Man and the Sea', 2000, 'excellent', 155, 'mystery');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (58, 'The Scarlet Letter', 2013, 'superb', 55, 'psychological');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (59, 'The Sun Also Rises', 2022, 'satisfactory', 85, 'mystery');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (60, 'The Chronicles of Narnia', 2027, 'superb', 10, 'romance');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (61, 'The Old Man and the Sea', 2014, 'stellar', 130, 'drama');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (62, 'The Outsiders', 1993, 'sublime', 15, 'silent');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (63, 'The Great Expectations', 1998, 'mediocre', 200, 'mystery');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (64, 'The Lord of the Rings', 2004, 'first-rate', 15, 'comedy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (65, 'The Metamorphosis', 2008, 'sublime', 170, 'superhero');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (66, 'Pride and Prejudice', 2015, 'first-rate', 200, 'educational');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (67, 'The Sound and the Fury', 2021, 'outstanding', 10, 'drama');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (68, 'The Shining', 2012, 'splendid', 110, 'teen');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (69, 'The Great Expectations', 2022, 'outstanding', 170, 'horror');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (70, 'The Sound and the Fury', 2018, 'unsatisfying', 40, 'musical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (71, 'The Girl on the Train', 2003, 'poor', 145, 'historical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (72, 'The Maze Runner', 2001, 'commendable', 105, 'time travel');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (73, 'Pride and Prejudice', 1994, 'stellar', 170, 'war');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (74, 'The Outsiders', 2023, 'mediocre', 190, 'historical');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (75, 'To Kill a Mockingbird', 2020, 'mediocre', 50, 'political');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (76, 'The Sound and the Fury', 2004, 'top-notch', 45, 'family');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (77, 'The Color Purple', 2014, 'awful', 195, 'silent');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (78, 'Brave New World', 2023, 'splendid', 60, 'teen');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (79, 'The Old Man and the Sea', 2010, 'phenomenal', 25, 'spy');
insert into tblFilms (filmID, title, yearReleased, rating, duration, genre) values (80, 'The Old Man and the Sea', 2027, 'subpar', 115, 'spy');